<a href="https://colab.research.google.com/github/Harshavignyan/ML_Content/blob/main/Handson_1_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# hands on 1 for data processing

In [2]:
import numpy as np
import pandas as pd

In [3]:
num_list = [1,2,3,4,5]

In [4]:
type(num_list)

list

In [5]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
# reshape it
arr = arr.reshape((2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# arr filled with zeros
np.zeros([3,3], dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [15]:
# arr with values 1 to 9
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# create a df using 1d list and 2d list
# 1d list
a = np.array([1,2,3], dtype='int32')
b = pd.DataFrame(a)
b

0
0  1
1  2
2  3

In [20]:
# 2d list
pd.DataFrame([[1,2,3],[4,5,6]], dtype='int32')

0  1  2
0  1  2  3
1  4  5  6

In [24]:
# a df from a dict
pd.DataFrame({'apple' : [1,2,3], 'banana' : [4,5,6]})

apple  banana
0      1       4
1      2       5
2      3       6